version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 072061963333.dkr.ecr.us-east-1.amazonaws.com
      - sudo yum install -y yarn
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...    
      - yarn build
      - docker build -t justin-resp .
      - docker tag justin-resp:latest 072061963333.dkr.ecr.us-east-1.amazonaws.com/justin-resp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 072061963333.dkr.ecr.us-east-1.amazonaws.com/justin-resp:latest